title: Shengchen Liu
author:
  name: shengchen-liu
  email: liu.sheng@gatech.edu
description: > # this means to ignore newlines until "show_excerpts:"
  Thi is Shengchen Liu's personal website.

show_excerpts: false # set to true to show excerpts on the homepage

baseurl : 
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github:  shengchen-liu
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: shengchen-liu-661a3380
    # pinterest: jekyll
    # youtube: jekyll
    youtube_channel: UCXpJSylFMTLtGKdHyh8RtwA
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
